<?php

require_once APPPATH . 'controllers/welcome.php';

/**
 * Test class for MY_Controller.
 * Generated by PHPUnit on 2012-07-28 at 04:07:52.
 */
class WelcomeTest extends DK_TestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
        $this->CI->load->model('usermodel');
    }
    
    /**
     * 测试从数据库编辑数据
     * 
     * @test
     */
    public function testMysql()
    {
        $post = $this->CI->usermodel->editUserMobile('10000010010','13957119235');
        $this->assertEquals(1, $post);
    }
    
    /**
     * 测试service
     * 
     * @test
     */
    public function testService()
    {
        $userinfo = $this->CI->usermodel->getUserInfo('1000001000');
        $this->assertEquals(23, count($userinfo));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        
    }

}

?>
