<?php

require_once EXTEND_PATH . 'core/DK_Router.php';

/**
 * Test class for DK_Router.
 * Generated by PHPUnit on 2012-07-27 at 07:52:47.
 */
class DK_RouterTest extends DK_TestCase {

    /**
     * @var DK_Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        parent::setUp();
        $this->object = DK_Router::getInstance();;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
        
    }

    /**
     * @covers DK_Router::getInstance
     * @todo Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->assertEquals($this->object, DK_Router::getInstance(), '对象不相等！');
    }

    /**
     * @covers DK_Router::parseRouter
     * @todo Implement testParseRouter().
     */
    public function testParseRouter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::testParse
     * @todo Implement testTestParse().
     */
    public function testTestParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::dispatcher
     * @todo Implement testDispatcher().
     */
    public function testDispatcher() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::reverseRemote
     * @todo Implement testReverseRemote().
     */
    public function testReverseRemote() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::reverseLocal
     * @todo Implement testReverseLocal().
     */
    public function testReverseLocal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::url
     * @todo Implement testUrl().
     */
    public function testUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers DK_Router::initConfig
     * @todo Implement testInitConfig().
     */
    public function testInitConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
